// Environment variable name classifier for Repo2Prod.
//
// Maps a single env-var NAME to one of the 5 EnvCategory buckets defined in
// src/core/types.ts. Classification is purely name-based.
//
// This file does NOT:
//   - read any file or directory
//   - open .env or any other file
//   - inspect or record env-var values (values may be secrets)
//   - make any LLM calls
//   - generate credentials or defaults

import type { EnvCategory } from '../core/types';

// ---------------------------------------------------------------------------
// Result type
// Kept local — it is not a shared contract and carries the internal "rule"
// field that callers can use to label fallback/unknown names in the UI.
// ---------------------------------------------------------------------------

/**
 * The result of classifying a single env-var name.
 * `rule` identifies which ruleset matched first (rules run in priority order).
 */
export interface EnvClassification {
  category: EnvCategory;
  required: boolean;
  rule:
    | 'infra'
    | 'local-secret'
    | 'safe-default'
    | 'optional-external'
    | 'external-credential'
    | 'fallback';
}

// ---------------------------------------------------------------------------
// Rule 1 — generated-local-infrastructure
// Checked FIRST so that e.g. POSTGRES_PASSWORD is treated as a locally
// generated Compose credential, not a user-supplied secret.
// ---------------------------------------------------------------------------

const INFRA_EXACT = new Set([
  'DATABASE_URL',
  'REDIS_URL',
  'CACHE_URL',
  'CELERY_BROKER_URL',
  'PGHOST',
  'PGPORT',
  'PGUSER',
  'PGPASSWORD',
  'PGDATABASE',
]);

const INFRA_PREFIXES = ['POSTGRES_', 'DB_', 'DATABASE_', 'REDIS_'];

// ---------------------------------------------------------------------------
// Rule 2 — generated-local-secret
// App-level secrets that Repo2Prod generates locally (e.g. Django SECRET_KEY).
// ---------------------------------------------------------------------------

const LOCAL_SECRET_EXACT = new Set([
  'SECRET_KEY',
  'DJANGO_SECRET_KEY',
  'JWT_SECRET',
  'JWT_SECRET_KEY',
  'SESSION_SECRET',
  'SIGNING_KEY',
]);

// ---------------------------------------------------------------------------
// Rule 3 — safe-inferred
// Well-known configuration knobs with safe dev-mode defaults.
// ---------------------------------------------------------------------------

const SAFE_DEFAULT_EXACT = new Set([
  'DEBUG',
  'DJANGO_DEBUG',
  'DJANGO_SETTINGS_MODULE',
  'ALLOWED_HOSTS',
  'DJANGO_ALLOWED_HOSTS',
  'CSRF_TRUSTED_ORIGINS',
  'DJANGO_CSRF_TRUSTED_ORIGINS',
  'PORT',
  'HOST',
  'LOG_LEVEL',
  'DJANGO_LOG_LEVEL',
  'TZ',
  'PYTHONUNBUFFERED',
  'PYTHONDONTWRITEBYTECODE',
  'ENV',
  'ENVIRONMENT',
  'DJANGO_ENV',
]);

// ---------------------------------------------------------------------------
// Rule 4 — optional-external
// Third-party observability/analytics integrations that are not required to
// run the app locally.
// ---------------------------------------------------------------------------

const OPTIONAL_SUFFIX = '_DSN';

const OPTIONAL_PREFIXES = ['SENTRY_', 'NEW_RELIC_', 'DD_', 'POSTHOG_', 'MIXPANEL_'];

// ---------------------------------------------------------------------------
// Rule 5 — user-secret-required (external credentials)
// Cloud providers and SaaS APIs that a real user must supply.
// ---------------------------------------------------------------------------

const EXTERNAL_CRED_PREFIXES = [
  'AWS_',
  'STRIPE_',
  'OPENAI_',
  'SENDGRID_',
  'TWILIO_',
  'GITHUB_',
  'GOOGLE_',
];

const EXTERNAL_CRED_SUFFIXES = [
  '_API_KEY',
  '_KEY',
  '_TOKEN',
  '_SECRET',
  '_PASSWORD',
  '_CREDENTIALS',
];

// ---------------------------------------------------------------------------
// Classifier — rules are evaluated in priority order, first match wins.
// ---------------------------------------------------------------------------

/**
 * Classify a single environment variable name into one of the 5 EnvCategory
 * buckets. Returns the category, whether the variable is required, and the
 * internal rule that matched.
 *
 * Rules run in this order:
 *   1. infra              (local Compose DB/cache — generated by Repo2Prod)
 *   2. local-secret       (app-level secrets — generated by Repo2Prod)
 *   3. safe-default       (well-known safe config knobs)
 *   4. optional-external  (observability integrations — not required locally)
 *   5. external-credential (real cloud/SaaS credentials — user must supply)
 *   6. fallback            (anything else — conservatively user-secret-required)
 *
 * The fallback is user-secret-required because an unknown name might be a
 * real credential. The user can downgrade it during configuration review.
 */
export function classifyEnvName(name: string): EnvClassification {
  // Rule 1 — infra: exact match or known DB/cache prefix
  if (INFRA_EXACT.has(name) || INFRA_PREFIXES.some(p => name.startsWith(p))) {
    return { category: 'generated-local-infrastructure', required: true, rule: 'infra' };
  }

  // Rule 2 — local-secret: exact match on well-known app secret names
  if (LOCAL_SECRET_EXACT.has(name)) {
    return { category: 'generated-local-secret', required: true, rule: 'local-secret' };
  }

  // Rule 3 — safe-default: exact match on well-known config knobs
  if (SAFE_DEFAULT_EXACT.has(name)) {
    return { category: 'safe-inferred', required: true, rule: 'safe-default' };
  }

  // Rule 4 — optional-external: observability suffix or known telemetry prefix
  if (name.endsWith(OPTIONAL_SUFFIX) || OPTIONAL_PREFIXES.some(p => name.startsWith(p))) {
    return { category: 'optional-external', required: false, rule: 'optional-external' };
  }

  // Rule 5 — external-credential: cloud/SaaS prefix or credential-bearing suffix
  if (
    EXTERNAL_CRED_PREFIXES.some(p => name.startsWith(p)) ||
    EXTERNAL_CRED_SUFFIXES.some(s => name.endsWith(s))
  ) {
    return { category: 'user-secret-required', required: true, rule: 'external-credential' };
  }

  // Rule 6 — fallback: unknown name, conservatively treated as a user secret
  return { category: 'user-secret-required', required: true, rule: 'fallback' };
}
